//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Connections
{
    using System;
    using System.Collections.Generic;
    
    public partial class viewAllMach
    {
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int Gender { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Name { get; set; }
        public string VerbName { get; set; }
        public int DayInWeek { get; set; }
        public System.DateTime TimeInDay { get; set; }
        public int EventID { get; set; }
        public bool requestIsActive { get; set; }
        public long RequestId1 { get; set; }
        public long RequestId2 { get; set; }
        public bool machIsActive { get; set; }
    }
}
